config/routes.rb
Rails.application.routes.draw do
  resources :proyects
  resources :workers do
    resources :allocations, only: [:create, :destroy]
  end
  root to: 'dashboardctrl#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/allocation.rb
class Allocation < ApplicationRecord
  belongs_to :worker
  belongs_to :proyect
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proyect.rb
class Proyect < ApplicationRecord
  has_many :allocations
  has_many :workers,  through: :allocations
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :allocations
  has_many :proyects,  through: :allocations
end

app/controllers/allocations_controller.rb
class AllocationsController < ApplicationController
  def create
    @worker = Worker.find(params[:worker_id])
    @proyect = Proyect.find(params[:proyect_id])
    @allocation = Allocation.new(worker_id: @worker.id , proyect_id: @proyect.id)
    @comprobation = Allocation.find_by(worker_id: @worker.id, proyect_id: @proyect.id)
    if @comprobation.nil?
      @allocation.save
      redirect_to worker_path(@worker)
    else
      redirect_to worker_path(@worker), alert: "no hemos podido ingresar lo solicitado"
    end
  end
  def destroy
    @worker = Worker.find(params[:worker_id])
    @proyect = Proyect.find(params[:proyect_id])
    @allocation = Allocation.find_by(worker_id: @worker.id, proyect_id: @proyect.id)
    @allocation.destroy
    redirect_to worker_path(@worker)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboardctrl_controller.rb
class DashboardctrlController < ApplicationController
  def index
    @workers = Worker.all
    @proyects = Proyect.all
  end
  def show

  end
  def create
  
  end
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :set_proyect, only: [:show, :edit, :update, :destroy]

  # GET /proyects
  # GET /proyects.json
  def index
    @proyects = Proyect.all
  end

  # GET /proyects/1
  # GET /proyects/1.json
  def show
  end

  # GET /proyects/new
  def new
    @proyect = Proyect.new
  end

  # GET /proyects/1/edit
  def edit
  end

  # POST /proyects
  # POST /proyects.json
  def create
    @proyect = Proyect.new(proyect_params)

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to @proyect, notice: 'Proyect was successfully created.' }
        format.json { render :show, status: :created, location: @proyect }
      else
        format.html { render :new }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyects/1
  # PATCH/PUT /proyects/1.json
  def update
    respond_to do |format|
      if @proyect.update(proyect_params)
        format.html { redirect_to @proyect, notice: 'Proyect was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyect }
      else
        format.html { render :edit }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1
  # DELETE /proyects/1.json
  def destroy
    @proyect.destroy
    respond_to do |format|
      format.html { redirect_to proyects_url, notice: 'Proyect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyect_params
      params.require(:proyect).permit(:name, :content)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @workers = Worker.all

  end

  # GET /workers/1
  # GET /workers/1.json
  def show
    @proyects = Proyect.all

  end

  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update
    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    @worker.destroy
    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:name, :last_name, :email)
    end
end

app/helpers/allocation_helper.rb
module AllocationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboardctrl_helper.rb
module DashboardctrlHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/dashboardctrl/index.html.erb
<div class="row">
  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Last name</th>
          <th>Email</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @workers.each do |worker| %>
          <tr>
            <td><%= worker.name %></td>
            <td><%= worker.last_name %></td>
            <td><%= worker.email %></td>
            <td><%= link_to 'Show', worker %></td>
            <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
            <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Worker', new_worker_path %>
  </div>
  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Content</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @proyects.each do |proyect| %>
          <tr>
            <td><%= proyect.name %></td>
            <td><%= proyect.content %></td>
            <td><%= link_to 'Show', proyect %></td>
            <td><%= link_to 'Edit', edit_proyect_path(proyect) %></td>
            <td><%= link_to 'Destroy', proyect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Proyect', new_proyect_path %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desafio37</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

app/views/proyects/_form.html.erb
<%= form_with(model: proyect, local: true) do |form| %>
  <% if proyect.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proyect.errors.count, "error") %> prohibited this proyect from being saved:</h2>

      <ul>
      <% proyect.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/proyects/edit.html.erb
<h1>Editing Proyect</h1>

<%= render 'form', proyect: @proyect %>

<%= link_to 'Show', @proyect %> |
<%= link_to 'Back', proyects_path %>

app/views/proyects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Proyects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proyects.each do |proyect| %>
      <tr>
        <td><%= proyect.name %></td>
        <td><%= proyect.content %></td>
        <td><%= link_to 'Show', proyect %></td>
        <td><%= link_to 'Edit', edit_proyect_path(proyect) %></td>
        <td><%= link_to 'Destroy', proyect, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proyect', new_proyect_path %>

app/views/proyects/new.html.erb
<h1>New Proyect</h1>

<%= render 'form', proyect: @proyect %>

<%= link_to 'Back', proyects_path %>

app/views/proyects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @proyect.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @proyect.content %>
</p>

<%= link_to 'Edit', edit_proyect_path(@proyect) %> |
<%= link_to 'Back', proyects_path %>

app/views/workers/_form.html.erb
<%= form_with(model: worker, local: true) do |form| %>
  <% if worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker.errors.count, "error") %> prohibited this worker from being saved:</h2>

      <ul>
      <% worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Show', @worker %> |
<%= link_to 'Back', workers_path %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= worker.name %></td>
        <td><%= worker.last_name %></td>
        <td><%= worker.email %></td>
        <td><%= link_to 'Show', worker %></td>
        <td><%= link_to 'Edit', edit_worker_path(worker) %></td>
        <td><%= link_to 'Destroy', worker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Worker', new_worker_path %>

app/views/workers/new.html.erb
<h1>New Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Back', workers_path %>

app/views/workers/show.html.erb
<div class="row">
  <div class="col-md-6">
    <table class="table">
      <thead>
        <tr>
          <th><strong>Name:</strong></th>
          <th><strong>Last name:</strong></th>
          <th> <strong>Email:</strong></th>
        </tr>

      </thead>
      <tbody>
        <td>
          <%= @worker.name %>
        </td>

        <td>
          <%= @worker.last_name %>
        </td>

        <td>
          <%= @worker.email %>
        </td>


      </tbody>

    </table>
    <%= link_to 'Edit', edit_worker_path(@worker) %> |
    <%= link_to 'Back', workers_path %>
  </div>
  <div class="col-md-6">
    <p id="notice"><%= notice %></p>
    <table class="table">
      <thead>
        <tr>
          <th> <strong> Proyect Name:</strong></th>
          <th> <strong>Content</strong></th>
        </tr>
      </thead>
      <tbody>
        <% @worker.proyects.each do |proyect| %>
        <td>
          <%= proyect.name %>
        </td>
        <td>
          <%= proyect.content %>
        </td>
        <td>
          <%= link_to "cancelar", worker_allocation_path(@worker.id, :proyect_id => proyect.id), method: :delete, data: { confirm: 'Are you sure?' }   %>
        </td>
      </tbody>

      <% end %>

    </table>

  </div>
</div>


<div class="row">
  <div class="col-md-6">
<br>
<br>
    <table class="table">
      <thead>
        <tr>
          <th><strong> Proyect disponible:</strong></th>
          <th> <strong>Content</strong></th>
        </tr>
      </thead>
      <tbody>
        <% @proyects.each do |proyect|  %>
        <td>
          <%= proyect.name %>
        </td>
        <td>
          <%= proyect.content %>
        </td>
        <td>
          <%= link_to "inscribir",  worker_allocations_path(@worker.id, :proyect_id => proyect.id), method: :post %>
        </td>
      </tbody>
      <% end %>
    </table>
  </div>


</div>